---
Name: foxystripe-integrations
---
Dynamic\FoxyStripe\Model\FoxyStripeSetting:
  extensions:
    - Dynamic\FoxyStripe\ORM\FoxyStripeIntegrationsSiteConfig
Dynamic\FoxyStripe\Controller\FoxyStripeController:
  extensions:
    - Dynamic\FoxyStripe\ORM\FoxyStripeIntegrationsExtension